### ISSUE TITLE
Faculty & degree programme & course summary view: MINTufy

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1051]
### Progreaass traacking

- [x] Basic summary for whole uni
- [x] Time selector
- [x] Time selector doesn't always show latest data wen changning, fix
- [x] Optimize, Avoin can crash server
- [x] Fix question result tooltips
- [x] Data update job
- [x] Ability to skip weird organisations (configurable)
- [x] Why numbers differ between org and child courses
- [x] How to sort in uni summary view?
- [x] How to sort flatlist? Infinite scroll not good
- [x] Make programme summary view similar to old
- [x] Link to organisation's page from summary
- [x] Question headers like old
- [x] Summary in organisation's page
- [x] Make it work for teachers
- [x] Make it work for programme & faculty staff
- [x] Open up to big bosses (one, dekaanit)
- [x] Viewing rights should use configurable values
- [x] Extended viewing rights: see parent/sibling organisation level? What about faculty level?
- [x] Fluid viewport: do it now or never
- [x] Make new the default
- [x] #1129
- [x] #1128
- [x] https://github.com/UniversityOfHelsinkiCS/palaute/issues/1130
