### ISSUE TITLE
Organisation semester survey

### ISSUE THREAD

**Issue by Keskimaki** [UniversityOfHelsinkiCS/palaute#1067]
- [x] FBT and custom CU and CUR associated to organisation
- [x] Prevent Updater from deleting new UFBTs, CUs and CURs
- [x] Create survey tab in organisation view
- [x] Add list of students via CSV, select administrative persons for survey
- [x] Surveys without university, organisation level questions
- [x] Change the text "Lisää uusi vastuuopettaja" to something like "Lisää kyselylle vastuuhenkilö"
- [x] Add information about the available delimeters for the student number input
- [x] Add indicators about ongoing feedbacks on the organisation surveys listing
- [x] Add status of the feedback amount (given / all students) on the organisation surveys listing
- [x] SORT the organisation surveys ASC by the end date of the feedback furthest end date first!
- [x] After creating a new organisation survey open up the summary page for the fbt
- [x] Disable deleting survey once feedback has been given
- [x] #1133 
- [x] Fix everything that breaks
