### ISSUE TITLE
Add support to those students who don't have AD-credentials

### ISSUE THREAD

**Issue by ollikehy** [UniversityOfHelsinkiCS/palaute#188]
12.10. update:

```
if username === id then student has no AD-account
```

- [x] Users who do not have AD get unique links in emails.

- [x] The link in user emails has url that has jwt which includes the user id.

- [x] Create new frontend pages which do not include navbar / navbar is almost empty.
- [x] Give feedback to a course
- [x] View counter feedback

- [x] Write middleware that parses jwt and fetches user

- [x] /api/noshibbo/* Routes are without shibboleth. Middleware is in front of these. Old controllers should also handle these

- [x] Logout removes jwt from localstorage

- [x] 403 page & explanation & handling

==

For those students who have registered to a course, but don't have ad-credentials f.ex. generate a unique link that allows them to send feedback

- [x] check if we can separate students with active AD-account

- only one answer per student
- only students who have registered can answer

Yes / No:

YES - Student without AD can give feedback to a course
YES - Student without AD can view counter feedback

NO - Student without AD can edit feedback
NO - Student without AD can see their courses listed on the front page
