### ISSUE TITLE
Testit

### ISSUE THREAD

**Issue by Jakousa** [UniversityOfHelsinkiCS/palaute#234]
- [x] wait for otto data
- [x] Create importer test data API
- [x] Do the master plan
- [x] Do the pipelines
- [x] Do the local test running environment
- [x] Do the acual shit
