### ISSUE TITLE
MEGATICKET: Use courseCode as the primary identifier in frontend for CourseUnits

### ISSUE THREAD

**Issue by Jakousa** [UniversityOfHelsinkiCS/palaute#246]
- [x] Change the frontend urls to use courseCode instead of CourseUnit id
- [x] Change the frontend to use courseCode instead of CourseUnit id
- [x] Change apis to respond as if courseCode was the unique identifier, merging data from multiple CourseUnits

Note: the database structure will probably stay the same as all resources from SISU still point at course unit ids. Proposed backend change would be:

Store all ids into a single "CourseUnit" resource in our database. (Array of strings?)

How would the proposed change behave if courses belong to different organizations/programmes?
