### ISSUE TITLE
END DATE time is 23.59pm?

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#898]
- [ ] Figure out timezone magic
- [ ] Make sure time is set to end/start of day when edited/updated
- [ ] Run migration to fix old dirty data
- [ ] Monitor updater new dates by logging
- [ ] do the acual shit

_Yritin tänään antaa yhdestä kursseistani kurssipalautetta. Palautelomakkeessa sekä siitä lähetetyssä sähköpostissa molemmissa luki lomakkeen olevan auki 11.11.2022 asti. Koska erillistä kellonaikaa ei missään oltu annettu, tämä tarkoittaa sitä, että lomake voi sulkeutua aikaisintaan 11.11.2022 kello 23.59. Olin venyttänyt palautteenannon viimeiseen päivään asti, sillä odotin luennoitsijan vielä julkaisevan jo päättyneen kurssin viimeiset vertaisarvioinnit, mitä hän ei tehnyt. Kun menin täyttämään lomaketta, lukikin siellä palautteenannon olevan suljettu ja vastausosiossa näkyvän graafin perusteella se on sulkeutunut jo aikaisin aamulla. En siis voinut enää antaa palautetta kurssistani, joka olisi sitä kipeästi tarvinnut monesta eri aiheesta. Tämä oli tietenkin hyvin turhauttavaa ja lannistaa minua yrittämästä antaa palautetta tulevaisuudessakaan. Koin palautteenannon ensimmäistä kertaa oikeasti tarpeelliseksi, enkä nyt voinutkaan sitä antaa._
