### ISSUE TITLE
Configuration for university-specific things

### ISSUE THREAD

**Issue by Keskimaki** [UniversityOfHelsinkiCS/palaute#991]
Using `node-config`, extract all uni specific fields to `config/default.js`

They will all be exposed in browser through webpack DefinePlugin, which populates the CONFIG variable ([here](https://github.com/UniversityOfHelsinkiCS/palaute/blob/0cfacc8f05f1a7e37661bbdc1641603694a7787a/config-overrides.js#L19))

### Todo

- [x] Make it possible to have a common config file for client/server
- [x] Move api urls to config
- [x] Move external links to translations
- [x] Move magic dates to config
- [x] Move general magic numbers to config
- [x] Dont use `src/config.js`
- [x] Figure out how to expose only necessery parts in browser
- [x] How to define which configuration file is used
- [x] Document the configuration format
